"""empty message

Revision ID: f23c5b85f934
Revises: 873ece709ea6
Create Date: 2023-04-09 20:38:37.880206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23c5b85f934'
down_revision = '873ece709ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.Column('Diameter', sa.String(length=250), nullable=True),
    sa.Column('atmósfera', sa.String(length=250), nullable=True),
    sa.Column('temperatura', sa.String(length=250), nullable=True),
    sa.Column('superficie', sa.String(length=250), nullable=True),
    sa.Column('Orbital_period', sa.String(length=250), nullable=True),
    sa.Column('Surface_water', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('Model', sa.String(length=250), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=250), nullable=True),
    sa.Column('consumables', sa.String(length=250), nullable=True),
    sa.Column('Cost_in_credits', sa.String(length=250), nullable=True),
    sa.Column('Created', sa.String(length=250), nullable=True),
    sa.Column('Manufacturer', sa.String(length=250), nullable=True),
    sa.Column('Length', sa.String(length=250), nullable=True),
    sa.Column('Max_atmosphering_speed', sa.String(length=250), nullable=True),
    sa.Column('Passengers', sa.String(length=250), nullable=True),
    sa.Column('Vehicle_classe', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('height', sa.String(length=250), nullable=True),
    sa.Column('year', sa.String(length=250), nullable=True),
    sa.Column('kg', sa.String(length=250), nullable=True),
    sa.Column('birthdate', sa.String(length=250), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('vehicles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['vehicles_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito_personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.Column('favorito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorito_id'], ['favoritos.id'], ),
    sa.ForeignKeyConstraint(['personaje_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito_planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('favorito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorito_id'], ['favoritos.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('favorito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorito_id'], ['favoritos.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito_vehicle')
    op.drop_table('favorito_planeta')
    op.drop_table('favorito_personaje')
    op.drop_table('people')
    op.drop_table('favoritos')
    op.drop_table('vehicles')
    op.drop_table('planet')
    # ### end Alembic commands ###
